database:
  host: "db.myvhzegeowsapjobfptt.supabase.co"
  port: 5432
  name: "postgres"
  user: "postgres"
  password: "Hiencaokgkg@@"
  timeout: 1000

redis:
  host: "100.127.255.19"
  port: 6379
  password: 'hiencaokgkg'
  pool:
    max: 20
    min: 5
    idle: 5

blacklist:
  - ""

general:
  debug: false
  okHttpRetry: 3
#  proxyVN: "https://api-vn.karyl.live/v2/server/proxy"
  proxyVN: "http://100.71.226.17:8081/v2/server/proxy"
  proxyVNBackup: 'http://100.71.226.17:8081/v2/server/proxy'
  aniListUrl: "https://api-us.karyl.live/consumet"
  userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"

bilibili:
  cookie: "SESSDATA=b95a7d18%2C1702910754%2Cc1b48%2A61"
